{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-push-stream-module.fullname" . }}
  labels:
    app: {{ include "nginx-push-stream-module.fullname" . }}
{{ if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{ end }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.service.nginxPort }}
    protocol: TCP
  selector:
    app: nginx-push-stream-module
{{ end }}
